export default {
  profileUsername: "zakisarchives",
  outputDir: "public/photography/instagram",
  tripOrder: [
    "catalina-island",
    "san-diego",
    "san-francisco",
    "yosemite",
    "chicago",
    "new-york-city",
    "durham",
    "blue-ridge",
    "cairo",
  ],
  trips: {
    "catalina-island": {
      name: "Catalina Island",
      country: "USA",
      coordinates: { lat: 33.3471, lng: -118.3211 },
      color: "#f4a261",
      description: "Harbor light, island facades, and a California answer to the Mediterranean.",
      match: {
        locations: ["catalina", "avalon"],
        captions: ["portofino", "avalon"],
      },
    },
    "san-diego": {
      name: "San Diego",
      country: "USA",
      coordinates: { lat: 32.7155, lng: -117.1585 },
      color: "#2a9d8f",
      description: "Campus returns, coastal color, and Southern California frames with clean evening light.",
      match: {
        locations: ["san diego", "ucsd"],
        captions: ["ucsd", "san diego"],
      },
    },
    "san-francisco": {
      name: "San Francisco",
      country: "USA",
      coordinates: { lat: 37.7749, lng: -122.4194 },
      color: "#ffb703",
      description: "Bridge views, city streets, and late-night architecture across San Francisco.",
      match: {
        locations: [
          "golden gate bridge",
          "golden gate park",
          "palace of fine arts",
          "san francisco",
        ],
        captions: ["san francisco", "sf"],
      },
    },
    yosemite: {
      name: "Yosemite",
      country: "USA",
      coordinates: { lat: 37.7469, lng: -119.5904 },
      color: "#84a98c",
      description: "Granite walls, valley light, and the first west-coast national park frames in the archive.",
      match: {
        locations: ["yosemite"],
        captions: ["yosemite"],
      },
    },
    chicago: {
      name: "Chicago",
      country: "USA",
      coordinates: { lat: 41.8781, lng: -87.6298 },
      color: "#ef476f",
      description: "Lakefront color, city geometry, and a late-summer Midwest run through Chicago.",
      match: {
        locations: ["chicago"],
        captions: ["chicago"],
      },
    },
    "new-york-city": {
      name: "New York City",
      country: "USA",
      coordinates: { lat: 40.8294, lng: -73.9264 },
      color: "#e63946",
      description: "Bronx stadium light and a fast crossover stop in New York City.",
      match: {
        locations: ["yankees stadium", "bronx"],
        captions: ["nyc", "bronx", "yankees"],
      },
    },
    durham: {
      name: "Durham",
      country: "USA",
      coordinates: { lat: 35.9954, lng: -78.9417 },
      color: "#3b82f6",
      description: "Campus rituals, jazz performances, and the closing stretch of student life at Duke.",
      match: {
        locations: ["duke", "durham", "wallace stadium"],
        captions: ["duke", "semester", "student"],
      },
    },
    "blue-ridge": {
      name: "Blue Ridge",
      country: "USA",
      coordinates: { lat: 35.7596, lng: -82.2717 },
      color: "#588157",
      description: "A fall-color run into the North Carolina mountains built around taking photos first.",
      match: {
        locations: ["blue ridge", "north carolina"],
        captions: ["n.c.", "mountains", "fall"],
      },
    },
    cairo: {
      name: "Cairo",
      country: "Egypt",
      coordinates: { lat: 30.0444, lng: 31.2357 },
      color: "#c46b3c",
      description: "Street scenes, old cafes, and winter light across Cairo.",
      match: {
        locations: ["cairo", "egypt"],
        captions: ["cairo", "egypt", "home"],
      },
    },
  },
  posts: {
    DSv2vh7Av_U: {
      tripId: "cairo",
      title: "A Walk Through Cairo",
      description: "Street scenes and city details from a winter walk through Cairo.",
      locationName: "Cairo, Egypt",
    },
    DSv2qL_gtCH: {
      tripId: "cairo",
      title: "Twenty Minutes From Home",
      description: "Historic Cairo through the lens of a place that still feels close to home.",
      locationName: "Cairo, Egypt",
    },
    DSHyv3kgua1: {
      tripId: "san-francisco",
      title: "Golden Gate Bridge",
      description: "Bridge frames, fog light, and a landmark that still earns the hype.",
    },
    DSHyJHugvxn: {
      tripId: "yosemite",
      title: "Yosemite",
      description: "A first Yosemite visit with wide valley frames and granite walls.",
    },
    DSHxz8EAlWJ: {
      tripId: "san-francisco",
      title: "SF at Night",
      description: "Night scenes across San Francisco with warmer city contrast.",
    },
    DSHxOmKgiVZ: {
      tripId: "san-francisco",
      title: "Palace of Fine Arts",
      description: "Architectural detail and Roman echoes at the Palace of Fine Arts.",
    },
    DSHu78NAu95: {
      tripId: "san-francisco",
      title: "San Francisco Streets",
      description: "Street light and neighborhood texture across San Francisco.",
      locationName: "San Francisco, California",
    },
    DSHutI4AgyI: {
      tripId: "durham",
      title: "Last Fall at Duke",
      description: "Loose frames from the final Duke fall semester.",
    },
    DQpiPCjibU9: {
      tripId: "blue-ridge",
      title: "Fall in North Carolina",
      description: "A mountains-first North Carolina trip built around autumn color.",
      locationName: "Blue Ridge Mountains, North Carolina",
    },
    "DP-5V6QjeEM": {
      tripId: "durham",
      title: "Duke Jazz Ensemble",
      description: "Stage frames from the Duke Jazz Ensemble spring performance.",
      locationName: "Durham, North Carolina",
    },
    "DP7-Gg1jbX-": {
      tripId: "san-diego",
      title: "Back at UCSD",
      description: "A return visit to UC San Diego with the camera doing most of the talking.",
    },
    DP76vaRgP4n: {
      tripId: "catalina-island",
      title: "Avalon",
      description: "Harbor views and pastel facades from Avalon on Catalina Island.",
    },
    DPQFzMsjWoA: {
      tripId: "new-york-city",
      title: "Duke x BISC NYC",
      description: "A Bronx stop for the Duke x BISC crossover episode in New York.",
      locationName: "Bronx, New York City",
    },
    DORrXbVCTQQ: {
      tripId: "chicago",
      title: "Chicago River Walk",
      description: "Chicago architecture, river edges, and the city that almost took first place.",
    },
    DORpu3kCRY1: {
      tripId: "chicago",
      title: "Chicago Lakefront",
      description: "Quiet lakefront frames on the same Chicago run.",
      locationName: "Chicago, Illinois",
    },
    DORoyPQCZPU: {
      tripId: "chicago",
      title: "Summer Road Frames",
      description: "Roadside Americana and car frames from the late-summer Midwest stretch.",
      locationName: "Chicago, Illinois",
    },
    DORHSVsjYLZ: {
      tripId: "chicago",
      title: "Summer Recap",
      description: "Loose summer fragments grouped into one last Chicago-era recap album.",
      locationName: "Chicago, Illinois",
    },
  },
};
